import { Inter } from "next/font/google";
import "./globals.css";
import { ContentGateProvider } from "@/components/ContentGate/ContentGateContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "LAMA DASHBOARD",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className={inter.className}>
        <ContentGateProvider>{children}</ContentGateProvider>
      </body>
    </html>
  );
}
